#!/bin/sh

set -e

cd $(dirname $0)

# Generate Schema files ...
OUTFILE="schema.go"

echo 'package storage' > $OUTFILE
echo '// !!! auto generated by generate.sh do not edit manually !!!' >> $OUTFILE
echo '' >> $OUTFILE
echo "const schema=\`" >> $OUTFILE
cat schema.sql >> $OUTFILE
echo "\`" >> $OUTFILE

# Create a database to generate the models
echo "Generating Models ..."
DBNAME="boiler.db"
if [ -e $DBNAME ]; then
    rm $DBNAME
fi

cat schema.sql | sqlite3 $DBNAME

sqlboiler --wipe --add-global-variants --no-context sqlite3

echo "Testing Model ..."
cp $DBNAME models/$DBNAME
go test ./models

rm $DBNAME
rm models/$DBNAME

